### ISSUE TITLE
Exception occurs when inserting nested Maps into document

### ISSUE THREAD

**Issue by twaddell** [y-crdt/ydotnet#99]
When attempting to insert a more complex nested map into a document the following exception occurs:
```
System.Runtime.InteropServices.SEHException : External component has thrown an exception.
   at YDotNet.Native.Types.Maps.MapChannel.Insert(IntPtr map, IntPtr transaction, IntPtr key, IntPtr value)
   at YDotNet.Document.Types.Maps.Map.Insert(Transaction transaction, String key, Input input) in X:\ydotnet\YDotNet\Document\Types\Maps\Map.cs:line 51
   at YDotNet.Tests.Unit.Maps.InsertTests.InsertNestedMap() in X:\ydotnet\Tests\YDotNet.Tests.Unit\Maps\InsertTests.cs:line 403
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

The following test case can be used to reproduce the issue:
```
[Test]
public void InsertNestedMap()
{
    // Arrange
    var doc = new Doc();
    var map = doc.Map("map");

    // Act
    var transaction = doc.WriteTransaction();
    var innerMap = Input.Map(new Dictionary<string, Input>
    {
        { "text", Input.String("Nested data") }
    });
    var outerMap = Input.Map(new Dictionary<string, Input>
    {
        { "innerMap", innerMap }
    });
    map.Insert(transaction, "outerMap", outerMap);
    var length = map.Length(transaction);
    transaction.Commit();

    // Assert
    Assert.That(length, Is.EqualTo(expected: 1));
}
```

In case it makes a difference I'm using the YDotNet.Native.Win32 native library.

Please do let me know if this is not the best approach to creating nested data structures as I'm relatively new to this library.

Thanks

**Comment by SebastianStehle** [comment]
Thanks a lot. This does not seem to be a problem with YDotNet, but with y-crdt, the rustl library. If you have experience with rust, it would be great if you could reproduce it there.

**Comment by Horusiath** [comment]
You probably won't reproduce it directly in rust (we have a lot of tests to confirm that working on nested collections work). We could try to check it out at the yffi level (C FFI bindings to Rust). Sometimes issues happen on that level.

**Comment by SebastianStehle** [comment]
Thanks for feedback @Horusiath . I would wait for this PR, because it changes a lot anyway: https://github.com/y-crdt/ydotnet/pull/94

**Comment by twaddell** [comment]
Sorry for the slow update, I'm new to Rust and it's been quite a few years since I've done any c++ so there may be some mistakes in the code snippets below.

- I've tested the original C# test case on the #94 branch and that fails there too.
- I've created the following test case in y-crdt which passes
```
  #[test]
  fn map_nested() {
      let d1 = Doc::with_client_id(1);
      let m1 = d1.get_or_insert_map("map");
      let mut t1 = d1.transact_mut();

      let mut innerMap: HashMap<String, _> = HashMap::new();
      innerMap.insert("text".to_owned(), "Nested data");
      
      let mut outerMap: HashMap<String, _> = HashMap::new();
      outerMap.insert("innerMap".to_owned(), MapPrelim::from(innerMap));

      m1.insert(&mut t1, "outerMap".to_owned(), MapPrelim::from(outerMap));
      
      assert_eq!(m1.len(&t1), 1);
  }
```

- The following test case in yffi fails
```
TEST_CASE("YMap multiple nested maps") {
    YDoc* doc = ydoc_new_with_id(1);
    Branch* map = ymap(doc, "map");
    YTransaction* txn = ydoc_write_transaction(doc, 0, NULL);

    char* key = (char*)"text";
    YInput value = yinput_string("Nested data");
    YInput innerMap = yinput_ymap(&key, &value, 1);

    char* key2 = (char*)"innerMap";
    YInput outerMap = yinput_ymap(&key2, &innerMap, 1);

    ymap_insert(map, txn, "outerMap", &outerMap);
    int length = ymap_len(map, txn);
    ytransaction_commit(txn);
    REQUIRE(length == 1);

    ydoc_destroy(doc);
}
```

```
thread '<unnamed>' panicked at yffi\src\lib.rs:2488:17:
Unrecognized YVal value tag.
```

- Simplifying the nesting in yffi will allow the test to pass
```
TEST_CASE("YMap nested map") {
    YDoc* doc = ydoc_new_with_id(1);
    Branch* map = ymap(doc, "map");
    YTransaction* txn = ydoc_write_transaction(doc, 0, NULL);

    char* key = (char*)"text";
    YInput value = yinput_string("Nested data");
    YInput innerMap = yinput_ymap(&key, &value, 1);

    ymap_insert(map, txn, "innerMap", &innerMap);
    int length = ymap_len(map, txn);
    ytransaction_commit(txn);
    REQUIRE(length == 1);

    ydoc_destroy(doc);
}
```

I hope that is useful let me know if there is any more I can do to help.

**Comment by SebastianStehle** [comment]
@LSViana It seems that it has been solved. I can work on that.
